# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import strata_ia_pb2 as strata__ia__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in strata_ia_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IaServiceStub(object):
    """---------------------------------------------------------------------------
    Services
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OcrPage = channel.unary_unary(
                '/strata.ia.v1.IaService/OcrPage',
                request_serializer=strata__ia__pb2.Crop.SerializeToString,
                response_deserializer=strata__ia__pb2.OcrResponse.FromString,
                _registered_method=True)
        self.ExtractTable = channel.unary_unary(
                '/strata.ia.v1.IaService/ExtractTable',
                request_serializer=strata__ia__pb2.Crop.SerializeToString,
                response_deserializer=strata__ia__pb2.TableResponse.FromString,
                _registered_method=True)
        self.DescribeImage = channel.unary_unary(
                '/strata.ia.v1.IaService/DescribeImage',
                request_serializer=strata__ia__pb2.Crop.SerializeToString,
                response_deserializer=strata__ia__pb2.ImageResponse.FromString,
                _registered_method=True)
        self.OcrFormula = channel.unary_unary(
                '/strata.ia.v1.IaService/OcrFormula',
                request_serializer=strata__ia__pb2.Crop.SerializeToString,
                response_deserializer=strata__ia__pb2.FormulaResponse.FromString,
                _registered_method=True)
        self.ProcessStream = channel.stream_stream(
                '/strata.ia.v1.IaService/ProcessStream',
                request_serializer=strata__ia__pb2.StreamCrop.SerializeToString,
                response_deserializer=strata__ia__pb2.StreamResult.FromString,
                _registered_method=True)


class IaServiceServicer(object):
    """---------------------------------------------------------------------------
    Services
    ---------------------------------------------------------------------------

    """

    def OcrPage(self, request, context):
        """Unary RPCs (one Crop in, one typed Result out).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OcrFormula(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessStream(self, request_iterator, context):
        """Bi-directional streaming for batch jobs. The Rust scheduler can push
        many crops at once and the IA server replies as soon as each one
        finishes — replies may arrive out of order, the correlation_id
        re-zips them on the caller side.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OcrPage': grpc.unary_unary_rpc_method_handler(
                    servicer.OcrPage,
                    request_deserializer=strata__ia__pb2.Crop.FromString,
                    response_serializer=strata__ia__pb2.OcrResponse.SerializeToString,
            ),
            'ExtractTable': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractTable,
                    request_deserializer=strata__ia__pb2.Crop.FromString,
                    response_serializer=strata__ia__pb2.TableResponse.SerializeToString,
            ),
            'DescribeImage': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeImage,
                    request_deserializer=strata__ia__pb2.Crop.FromString,
                    response_serializer=strata__ia__pb2.ImageResponse.SerializeToString,
            ),
            'OcrFormula': grpc.unary_unary_rpc_method_handler(
                    servicer.OcrFormula,
                    request_deserializer=strata__ia__pb2.Crop.FromString,
                    response_serializer=strata__ia__pb2.FormulaResponse.SerializeToString,
            ),
            'ProcessStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ProcessStream,
                    request_deserializer=strata__ia__pb2.StreamCrop.FromString,
                    response_serializer=strata__ia__pb2.StreamResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'strata.ia.v1.IaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('strata.ia.v1.IaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IaService(object):
    """---------------------------------------------------------------------------
    Services
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def OcrPage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strata.ia.v1.IaService/OcrPage',
            strata__ia__pb2.Crop.SerializeToString,
            strata__ia__pb2.OcrResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strata.ia.v1.IaService/ExtractTable',
            strata__ia__pb2.Crop.SerializeToString,
            strata__ia__pb2.TableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DescribeImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strata.ia.v1.IaService/DescribeImage',
            strata__ia__pb2.Crop.SerializeToString,
            strata__ia__pb2.ImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OcrFormula(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strata.ia.v1.IaService/OcrFormula',
            strata__ia__pb2.Crop.SerializeToString,
            strata__ia__pb2.FormulaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/strata.ia.v1.IaService/ProcessStream',
            strata__ia__pb2.StreamCrop.SerializeToString,
            strata__ia__pb2.StreamResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
