"""Cross-language schema validation.

Loads ``docs/schema/strata-document.schema.json`` (generated by
``cargo run -p xtask -- gen-schema``) and validates every
``tests/fixtures/expected/*.golden.json`` against it. Skips gracefully when
neither the schema nor the goldens exist yet (early in development they don't).

See ``docs/task/tareas.md`` T1.3.A1.3.2.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SCHEMA_PATH = REPO_ROOT / "docs" / "schema" / "strata-document.schema.json"
EXPECTED_DIR = REPO_ROOT / "tests" / "fixtures" / "expected"


def _golden_files() -> list[Path]:
    if not EXPECTED_DIR.exists():
        return []
    return sorted(EXPECTED_DIR.glob("*.golden.json"))


@pytest.fixture(scope="module")
def schema() -> dict:
    if not SCHEMA_PATH.exists():
        pytest.skip(
            f"{SCHEMA_PATH.relative_to(REPO_ROOT)} not generated yet — "
            "run `cargo run -p xtask -- gen-schema`."
        )
    return json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))


def test_schema_is_valid_json_schema(schema: dict) -> None:
    """The generated file is itself a valid Draft 2020-12 JSON Schema."""
    import jsonschema
    from jsonschema.validators import validator_for

    validator_cls = validator_for(schema)
    validator_cls.check_schema(schema)
    # Sanity: every Document needs `meta` and `pages`.
    assert "Document" in (schema.get("$defs", {}).keys() | {schema.get("title", "")})


@pytest.mark.parametrize("golden", _golden_files(), ids=lambda p: p.name)
def test_golden_validates(golden: Path, schema: dict) -> None:
    import jsonschema

    payload = json.loads(golden.read_text(encoding="utf-8"))
    jsonschema.validate(instance=payload, schema=schema)


def test_at_least_one_golden_or_skip() -> None:
    """Soft signal — once goldens exist, this test stops being a no-op."""
    if not _golden_files():
        pytest.skip(
            "no golden files in tests/fixtures/expected/* yet — "
            "regenerate with `strata parse --regen-expected` after F10.T10.1."
        )
