"""Throughput benchmark — pages/second and GB/hour over the corpus.

Plan Maestro §15.T10.3 — runs the `strata` CLI against the fixture
corpus with each Triage profile, reports latency p50 / p95 / p99 to
``docs/benchmarks/throughput.md``.

The Rust-side `cargo bench` complement (criterion) covers the Rust
core in isolation; this script measures the full end-to-end pipeline
including the IA bridge.

Usage::

    uv run python benches/batch.py                          # all 3 profiles
    uv run python benches/batch.py --profile balanced --runs 5
"""

from __future__ import annotations

import argparse
import logging
import shutil
import statistics
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
FIXTURES_PDFS = REPO_ROOT / "tests" / "fixtures" / "pdfs"
REPORT = REPO_ROOT / "docs" / "benchmarks" / "throughput.md"

logger = logging.getLogger("throughput")


@dataclass
class Sample:
    pdf: str
    profile: str
    pages: int
    seconds: float

    @property
    def pages_per_second(self) -> float:
        return self.pages / self.seconds if self.seconds > 0 else 0.0


def count_pages(pdf: Path) -> int:
    """Best-effort page count without pulling pypdf. Reads the file and
    counts `/Type /Page` tokens; close enough for benchmark labelling."""
    try:
        data = pdf.read_bytes()
    except OSError:
        return 0
    return data.count(b"/Type /Page") or 1


def run_once(strata_bin: str, pdf: Path, profile: str, tmp: Path) -> Sample:
    out = tmp / pdf.stem
    out.mkdir(parents=True, exist_ok=True)
    start = time.perf_counter()
    result = subprocess.run(
        [
            strata_bin,
            "parse",
            "--input",
            str(pdf),
            "--output",
            str(out),
            "--format",
            "md+json",
            "--profile",
            profile,
        ],
        capture_output=True,
        text=True,
        timeout=900,
    )
    seconds = time.perf_counter() - start
    if result.returncode != 0:
        logger.warning("strata parse failed: %s", result.stderr[:300])
        return Sample(pdf.name, profile, count_pages(pdf), seconds)
    return Sample(pdf.name, profile, count_pages(pdf), seconds)


def aggregate(samples: list[Sample]) -> dict[str, float]:
    if not samples:
        return {"p50": 0.0, "p95": 0.0, "p99": 0.0, "pages_per_second_median": 0.0}
    secs = sorted(s.seconds for s in samples)
    pps = [s.pages_per_second for s in samples]
    return {
        "p50": _percentile(secs, 50),
        "p95": _percentile(secs, 95),
        "p99": _percentile(secs, 99),
        "pages_per_second_median": statistics.median(pps) if pps else 0.0,
    }


def _percentile(sorted_values: list[float], p: int) -> float:
    if not sorted_values:
        return 0.0
    idx = max(0, min(len(sorted_values) - 1, round((p / 100) * (len(sorted_values) - 1))))
    return sorted_values[idx]


def render_report(by_profile: dict[str, list[Sample]]) -> str:
    lines = [
        "# Throughput Benchmark",
        "",
        "Generated by `benches/batch.py`. Plan Maestro §15.T10.3.",
        "",
        "AC reference: ≥ 30 pág/s in `fast` and ≥ 3 pág/s in `scientific`",
        "on the reference machine (16 cores + 1×RTX 4090).",
        "",
        "| profile | runs | p50 (s) | p95 (s) | p99 (s) | median pages/sec |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for profile, samples in by_profile.items():
        agg = aggregate(samples)
        lines.append(
            f"| {profile} | {len(samples)} | {agg['p50']:.2f} | "
            f"{agg['p95']:.2f} | {agg['p99']:.2f} | {agg['pages_per_second_median']:.2f} |"
        )

    lines.append("")
    lines.append("## Per-fixture latency")
    lines.append("")
    lines.append("| fixture | profile | pages | seconds | pages/sec |")
    lines.append("| --- | --- | --- | --- | --- |")
    for samples in by_profile.values():
        for s in samples:
            lines.append(
                f"| `{s.pdf}` | {s.profile} | {s.pages} | {s.seconds:.2f} | {s.pages_per_second:.2f} |"
            )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile", help="restrict to one profile (default: all three)")
    parser.add_argument("--runs", type=int, default=3, help="repetitions per (pdf, profile) pair")
    parser.add_argument("--report", type=Path, default=REPORT)
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
    )

    strata_bin = shutil.which("strata")
    if strata_bin is None:
        logger.error("`strata` binary not on PATH; bench would only measure timeout overhead")
        return 2

    pdfs = sorted(FIXTURES_PDFS.glob("*.pdf"))
    if not pdfs:
        logger.error("no fixtures under %s", FIXTURES_PDFS)
        return 3

    profiles = [args.profile] if args.profile else ["fast", "balanced", "scientific"]
    tmp = REPO_ROOT / "_throughput_out"
    if tmp.exists():
        shutil.rmtree(tmp)
    tmp.mkdir()

    by_profile: dict[str, list[Sample]] = {}
    for profile in profiles:
        by_profile[profile] = []
        for pdf in pdfs:
            for run in range(args.runs):
                logger.info("profile=%s pdf=%s run=%d/%d", profile, pdf.name, run + 1, args.runs)
                by_profile[profile].append(run_once(strata_bin, pdf, profile, tmp))

    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(render_report(by_profile), encoding="utf-8")
    logger.info("wrote %s", args.report.relative_to(REPO_ROOT))

    shutil.rmtree(tmp, ignore_errors=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
