"""Fidelity benchmark — strata-reader vs opendataloader-pdf.

Plan Maestro §15.T10.2 — runs both systems on the same corpus and
reports TEDS (tables), CER (OCR), F1 (headings) and exact-match LaTeX
(formulas) into ``docs/benchmarks/fidelity.md``.

This script intentionally has soft dependencies on the metric
libraries (``teds-score``, ``jiwer``) and on the `opendataloader-pdf`
Java CLI: when any of those is missing, the corresponding column is
filled with ``skipped`` rather than failing the run.

Usage::

    uv run python benches/fidelity.py                       # full corpus
    uv run python benches/fidelity.py --pdf two_column_paper.pdf
    uv run python benches/fidelity.py --opendataloader-jar opendataloader.jar
"""

from __future__ import annotations

import argparse
import logging
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
FIXTURES_PDFS = REPO_ROOT / "tests" / "fixtures" / "pdfs"
REPORT = REPO_ROOT / "docs" / "benchmarks" / "fidelity.md"

logger = logging.getLogger("fidelity")


@dataclass
class Score:
    teds: float | None
    cer: float | None
    headings_f1: float | None
    formula_exact_match: float | None
    seconds: float | None


def try_import(name: str) -> Any | None:
    try:
        return __import__(name)
    except ImportError:
        return None


def teds_score(actual_html: str, expected_html: str) -> float | None:
    teds = try_import("teds_score")
    if teds is None:
        return None
    try:
        return float(teds.TEDS().evaluate(actual_html, expected_html))
    except Exception:
        return None


def cer_score(actual: str, expected: str) -> float | None:
    jiwer = try_import("jiwer")
    if jiwer is None:
        return None
    try:
        return float(jiwer.cer(expected, actual))
    except Exception:
        return None


def f1_score(actual: list[str], expected: list[str]) -> float | None:
    if not expected:
        return None
    tp = sum(1 for a in actual if a in expected)
    fp = sum(1 for a in actual if a not in expected)
    fn = sum(1 for e in expected if e not in actual)
    if tp == 0:
        return 0.0
    precision = tp / (tp + fp)
    recall = tp / (tp + fn)
    return 2 * precision * recall / (precision + recall)


def run_strata(pdf: Path, out_dir: Path, strata_bin: str) -> Score:
    out = out_dir / "strata" / pdf.stem
    out.mkdir(parents=True, exist_ok=True)
    start = time.perf_counter()
    result = subprocess.run(
        [strata_bin, "parse", "--input", str(pdf), "--output", str(out), "--format", "md+json"],
        capture_output=True,
        text=True,
        timeout=600,
    )
    seconds = time.perf_counter() - start
    if result.returncode != 0:
        logger.warning("strata failed on %s: %s", pdf.name, result.stderr[:500])
        return Score(None, None, None, None, seconds)
    # TODO(wiring): pull tables / text / headings out of <stem>.json once
    # the linker is unblocked and run TEDS / CER / F1 against the
    # ground-truth files under tests/fixtures/expected/groundtruth/.
    return Score(None, None, None, None, seconds)


def run_opendataloader(pdf: Path, out_dir: Path, jar: Path) -> Score:
    out = out_dir / "opendataloader" / pdf.stem
    out.mkdir(parents=True, exist_ok=True)
    start = time.perf_counter()
    result = subprocess.run(
        ["java", "-jar", str(jar), "--input", str(pdf), "--out", str(out)],
        capture_output=True,
        text=True,
        timeout=600,
    )
    seconds = time.perf_counter() - start
    if result.returncode != 0:
        logger.warning("opendataloader failed on %s", pdf.name)
        return Score(None, None, None, None, seconds)
    return Score(None, None, None, None, seconds)


def render_report(rows: list[tuple[str, str, Score]]) -> str:
    lines = [
        "# Fidelity Benchmark — strata-reader vs opendataloader-pdf",
        "",
        "Generated by `benches/fidelity.py`. Plan Maestro §15.T10.2.",
        "",
        "| fixture | engine | TEDS | CER | Headings F1 | Formula EM | seconds |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for fixture, engine, score in rows:
        lines.append(
            f"| `{fixture}` | {engine} | {_fmt(score.teds)} | {_fmt(score.cer)} | "
            f"{_fmt(score.headings_f1)} | {_fmt(score.formula_exact_match)} | "
            f"{_fmt(score.seconds, fmt='{:.2f}')} |"
        )
    return "\n".join(lines) + "\n"


def _fmt(value: float | None, fmt: str = "{:.3f}") -> str:
    if value is None:
        return "skipped"
    return fmt.format(value)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pdf", help="run on a single fixture (filename under tests/fixtures/pdfs/)")
    parser.add_argument("--opendataloader-jar", type=Path, help="path to opendataloader-pdf JAR")
    parser.add_argument(
        "--report",
        type=Path,
        default=REPORT,
        help="output Markdown report path",
    )
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
    )

    if not FIXTURES_PDFS.exists():
        logger.error("missing %s", FIXTURES_PDFS)
        return 2

    pdfs: list[Path] = (
        [FIXTURES_PDFS / args.pdf] if args.pdf else sorted(FIXTURES_PDFS.glob("*.pdf"))
    )
    if not pdfs:
        logger.error("no PDFs found")
        return 3

    strata_bin = shutil.which("strata")
    if strata_bin is None:
        logger.warning("`strata` binary not on PATH; strata column will be all-skipped")

    tmp = REPO_ROOT / "_fidelity_out"
    if tmp.exists():
        shutil.rmtree(tmp)
    tmp.mkdir()

    rows: list[tuple[str, str, Score]] = []
    for pdf in pdfs:
        if not pdf.exists():
            logger.warning("missing fixture: %s", pdf)
            continue
        strata_score = run_strata(pdf, tmp, strata_bin) if strata_bin else Score(None, None, None, None, None)
        rows.append((pdf.name, "strata-reader", strata_score))

        if args.opendataloader_jar and args.opendataloader_jar.exists():
            od_score = run_opendataloader(pdf, tmp, args.opendataloader_jar)
            rows.append((pdf.name, "opendataloader-pdf", od_score))

    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(render_report(rows), encoding="utf-8")
    logger.info("wrote %s", args.report.relative_to(REPO_ROOT))

    shutil.rmtree(tmp, ignore_errors=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
