"""Visual-regression bench — diff annotated PDFs against pixel goldens.

Plan Maestro §15.T10.4 — runs `strata annotate` (CLI hook to be added
once the linker is unblocked) on every fixture, rasterizes the result
and compares page-by-page against committed PNG goldens. AC: pixel
diff ≤ 1% per page (tolerates anti-aliasing).

Hard-dependencies (Pillow only — already in the base deps). The
strata CLI invocation is optional: when `strata annotate` is missing
from PATH the script emits an empty report explaining the skip
instead of crashing the run.

Outputs:
- ``docs/benchmarks/visual_regression.md``  — table of per-fixture diff %.
- ``_visual_diff/<stem>/page-N.diff.png``    — side-by-side diff images
  for pages whose diff exceeded the threshold (helps PR reviewers).
"""

from __future__ import annotations

import argparse
import logging
import shutil
import subprocess
import sys
from pathlib import Path

from PIL import Image, ImageChops

REPO_ROOT = Path(__file__).resolve().parents[1]
FIXTURES_PDFS = REPO_ROOT / "tests" / "fixtures" / "pdfs"
GOLDEN_DIR = REPO_ROOT / "tests" / "fixtures" / "expected" / "annotated_pages"
REPORT = REPO_ROOT / "docs" / "benchmarks" / "visual_regression.md"
DIFF_OUT = REPO_ROOT / "_visual_diff"

THRESHOLD_PCT = 1.0

logger = logging.getLogger("visual_regression")


def pixel_diff_percent(a: Image.Image, b: Image.Image) -> float:
    """Return the fraction of pixels (0..100) that differ between the
    two RGB images. Sizes that don't match return 100% immediately —
    the caller treats that as a hard fail."""
    if a.size != b.size:
        return 100.0
    diff = ImageChops.difference(a.convert("RGB"), b.convert("RGB"))
    bbox = diff.getbbox()
    if bbox is None:
        return 0.0
    # Count non-zero pixels.
    histogram = diff.histogram()
    # Channels are concatenated (R G B for RGB images).
    total_pixels = a.size[0] * a.size[1]
    non_zero = sum(histogram[1:256]) + sum(histogram[257:512]) + sum(histogram[513:768])
    if total_pixels == 0:
        return 0.0
    return 100.0 * non_zero / (total_pixels * 3)


def render_pdf_pages(pdf: Path, out_dir: Path, dpi: int = 100) -> list[Path]:
    """Render every page to PNG via the bundled `pdftoppm` if available,
    otherwise via Pillow's experimental PDF reader (fallback used only
    when the system tool is missing).
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    pdftoppm = shutil.which("pdftoppm")
    if pdftoppm is None:
        logger.warning("pdftoppm not on PATH; skipping %s", pdf.name)
        return []
    prefix = out_dir / pdf.stem
    subprocess.run(
        [pdftoppm, "-png", "-r", str(dpi), str(pdf), str(prefix)],
        check=True,
        capture_output=True,
    )
    return sorted(out_dir.glob(f"{pdf.stem}-*.png"))


def run_once(pdf: Path, strata_bin: str | None) -> tuple[Path | None, list[Path]]:
    """Build the annotated PDF (when strata is available) and render
    every page. Returns (annotated_pdf, rendered_png_paths)."""
    annotated_dir = DIFF_OUT / pdf.stem
    annotated_dir.mkdir(parents=True, exist_ok=True)
    annotated_pdf = annotated_dir / f"{pdf.stem}.annotated.pdf"
    if strata_bin:
        try:
            subprocess.run(
                [strata_bin, "annotate", "--input", str(pdf), "--output", str(annotated_pdf)],
                check=True,
                capture_output=True,
                text=True,
                timeout=300,
            )
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as exc:
            logger.warning("strata annotate failed on %s: %s", pdf.name, exc)
            return None, []
    else:
        return None, []
    return annotated_pdf, render_pdf_pages(annotated_pdf, annotated_dir)


def render_report(rows: list[tuple[str, str, float, str]]) -> str:
    lines = [
        "# Visual-regression Benchmark",
        "",
        "Generated by `benches/visual_regression.py`. Plan Maestro §15.T10.4.",
        "",
        f"AC: diff ≤ {THRESHOLD_PCT:.1f}% per page (tolerates anti-aliasing).",
        "",
        "| fixture | page | diff % | verdict |",
        "| --- | --- | --- | --- |",
    ]
    for fixture, page, diff_pct, verdict in rows:
        lines.append(f"| `{fixture}` | {page} | {diff_pct:.3f} | {verdict} |")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--report", type=Path, default=REPORT)
    parser.add_argument("--threshold", type=float, default=THRESHOLD_PCT)
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
    )

    strata_bin = shutil.which("strata")
    if strata_bin is None:
        logger.warning("`strata` not on PATH — generating an empty report explaining the skip")
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(
            "# Visual-regression Benchmark\n\n"
            "_skipped — strata binary not on PATH. "
            "Build with `cargo build -p strata-cli --release`._\n",
            encoding="utf-8",
        )
        return 0

    pdfs = sorted(FIXTURES_PDFS.glob("*.pdf"))
    if not pdfs:
        logger.error("no fixtures under %s", FIXTURES_PDFS)
        return 3

    if DIFF_OUT.exists():
        shutil.rmtree(DIFF_OUT)
    DIFF_OUT.mkdir()

    rows: list[tuple[str, str, float, str]] = []
    for pdf in pdfs:
        _annotated, actual_pages = run_once(pdf, strata_bin)
        if not actual_pages:
            continue
        golden_subdir = GOLDEN_DIR / pdf.stem
        if not golden_subdir.exists():
            logger.warning("no golden pages for %s — skipping", pdf.name)
            continue
        for page_idx, actual in enumerate(actual_pages, start=1):
            golden = golden_subdir / f"page-{page_idx}.png"
            if not golden.exists():
                rows.append((pdf.name, str(page_idx), 100.0, "no-golden"))
                continue
            with Image.open(actual) as a, Image.open(golden) as g:
                diff = pixel_diff_percent(a, g)
            verdict = "ok" if diff <= args.threshold else "DRIFT"
            rows.append((pdf.name, str(page_idx), diff, verdict))

    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(render_report(rows), encoding="utf-8")
    logger.info("wrote %s", args.report.relative_to(REPO_ROOT))

    failures = [r for r in rows if r[3] == "DRIFT"]
    if failures:
        logger.error("%d page(s) over the %s%% threshold", len(failures), args.threshold)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
